version: "3"

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"

  app:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - dbt

  dbt:
    build:
      context: mysql
      dockerfile: Dockerfile
    platform: linux/amd64
    command: --innodb-use-native-aio=0
    container_name: dbt
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodepeople
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
